### ISSUE TITLE
崩溃反馈 一打开就崩溃

### ISSUE THREAD

**Issue by Zhiyuan36** [LoCyan-Team/LoCyanFrpCSDesktop#8]
### 当前使用的LocyanFrp版本

2.2.0 alpha2

### 崩溃日志

无日志，打开及崩溃

### 复现操作

1. 打开
2. 崩溃

（注：有时候会打开一个chrome）

**Comment by Daiyangcheng** [comment]
我们好像不存在 `2.2.0 alpha2` 这个版本？

**Comment by Daiyangcheng** [comment]
preview 版本存在问题请自行修改源代码，不予提供解释和支持
